import csv
from dataclasses import dataclass
from datetime import datetime, time
from decimal import Decimal, InvalidOperation
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils import timezone

from deposits.models import DepositSubmission
from groupcore.models import MemberProfile, SavingsAccount
from loans.models import LoanRepayment, LoanRequest


DATE_FORMATS = ('%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y')
TIME_FORMATS = ('%H:%M:%S', '%H:%M')
REPORT_FIELDNAMES = [
    'source',
    'row_number',
    'reference',
    'status',
    'username',
    'account_label',
    'amount',
    'message',
]


@dataclass
class LoanPayload:
    row_number: int
    report_index: int
    reference: str
    username: str
    account_label: str
    issue_date: object
    approved_on: object
    principal: Decimal
    monthly_interest_rate: Decimal
    duration_months: int | None
    purpose: str
    remarks: str


@dataclass
class RepaymentPayload:
    row_number: int
    report_index: int
    reference: str
    deposit_reference: str
    loan_reference: str
    username: str
    account_label: str
    paid_on: object
    payment_week: object
    payment_time: object
    amount: Decimal
    notes: str


class Command(BaseCommand):
    help = 'Validate and import historical approved loans and repayments. Dry-run by default.'

    def add_arguments(self, parser):
        parser.add_argument('--loans', required=True, help='CSV file generated by prepare_loan_schedule_import.')
        parser.add_argument('--repayments', required=True, help='CSV file generated by prepare_loan_schedule_import.')
        parser.add_argument('--report', default='imports/loan_schedule_2026_import_report.csv')
        parser.add_argument('--commit', action='store_true', help='Write validated rows to the database.')
        parser.add_argument('--submitted-by', help='Username to store as recorder/reviewer for imported repayment rows.')
        parser.add_argument('--batch', help='Import batch label.')

    def handle(self, *args, **options):
        loan_rows = self._load_csv(Path(options['loans']))
        repayment_rows = self._load_csv(Path(options['repayments']))
        report_rows = []

        loan_payloads, loan_errors = self._validate_loans(loan_rows, report_rows)
        repayment_payloads, repayment_errors = self._validate_repayments(
            repayment_rows,
            loan_payloads,
            report_rows,
        )
        errors = loan_errors + repayment_errors
        report_path = Path(options['report'])
        if errors:
            self._write_report(report_path, report_rows)
            raise CommandError(
                f"Historical loan import blocked: {len(errors)} row(s) need correction. Review {report_path}."
            )

        if not options['commit']:
            self._write_report(report_path, report_rows)
            self.stdout.write(
                self.style.SUCCESS(
                    f"Dry run passed. No data was changed. Review {report_path}, then rerun with --commit."
                )
            )
            return

        batch_label = options.get('batch') or f"historical-loans-{timezone.localtime().strftime('%Y%m%d-%H%M%S')}"
        submitted_by = self._get_submitted_by(options.get('submitted_by'))
        with transaction.atomic():
            self._import_loans(loan_payloads, report_rows, batch_label)
            self._import_repayments(repayment_payloads, report_rows, batch_label, submitted_by)

        self._write_report(report_path, report_rows)
        self.stdout.write(
            self.style.SUCCESS(
                f"Historical loan import completed. Review {report_path} for imported, existing, and skipped rows."
            )
        )

    def _validate_loans(self, rows, report_rows):
        errors = []
        payloads = []
        seen_references = set()
        existing_references = set(
            LoanRequest.objects
            .filter(import_reference__isnull=False)
            .values_list('import_reference', flat=True)
        )
        existing_references = {reference.lower() for reference in existing_references}

        for index, row in enumerate(rows, start=2):
            reference = (row.get('loan_reference') or '').strip()
            username = (row.get('username') or '').strip()
            account_label = (row.get('account_label') or '').strip()
            row_errors = []

            if not reference:
                row_errors.append('loan_reference is required')
            elif len(reference) > 120:
                row_errors.append('loan_reference is longer than 120 characters')
            elif reference.lower() in seen_references:
                row_errors.append(f'duplicate loan_reference in file: {reference}')
            else:
                seen_references.add(reference.lower())

            member = MemberProfile.objects.filter(username=username).first()
            if not member:
                row_errors.append(f'member username not found: {username}')

            account = None
            if member:
                account = SavingsAccount.objects.filter(owner=member, label__iexact=account_label).first()
            if not account:
                row_errors.append(f'savings account not found for member: {account_label}')

            issue_date = self._parse_date(row.get('issue_date'))
            approved_on = self._parse_date(row.get('approved_on')) or issue_date
            if not issue_date:
                row_errors.append('issue_date is required and must be a valid date')

            principal = self._parse_amount(row.get('principal'))
            if principal <= 0:
                row_errors.append('principal must be greater than zero')

            monthly_rate = self._parse_amount(row.get('monthly_interest_rate') or '2.00')
            if monthly_rate < 0:
                row_errors.append('monthly_interest_rate cannot be negative')

            duration_months = self._parse_optional_int(row.get('duration_months'))
            if duration_months is not None and duration_months <= 0:
                row_errors.append('duration_months must be blank or greater than zero')

            status = 'ERROR' if row_errors else (
                'VALID_EXISTING_LOAN' if reference.lower() in existing_references else 'VALID_NEW_LOAN'
            )
            report_index = self._append_report_row(
                report_rows,
                source='loan',
                row_number=index,
                reference=reference,
                status=status,
                username=username,
                account_label=account_label,
                amount=principal,
                message='; '.join(row_errors),
            )
            if row_errors:
                errors.extend(row_errors)
                continue

            payloads.append(LoanPayload(
                row_number=index,
                report_index=report_index,
                reference=reference,
                username=username,
                account_label=account_label,
                issue_date=issue_date,
                approved_on=approved_on,
                principal=principal,
                monthly_interest_rate=monthly_rate,
                duration_months=duration_months,
                purpose=(row.get('purpose') or '').strip(),
                remarks=(row.get('remarks') or '').strip(),
            ))

        return payloads, errors

    def _validate_repayments(self, rows, loan_payloads, report_rows):
        errors = []
        payloads = []
        seen_references = set()
        loan_references = {payload.reference.lower() for payload in loan_payloads}
        loan_references.update(
            reference.lower()
            for reference in LoanRequest.objects
            .filter(import_reference__isnull=False)
            .values_list('import_reference', flat=True)
        )
        existing_repayments = set(
            reference.lower()
            for reference in LoanRepayment.objects
            .filter(import_reference__isnull=False)
            .values_list('import_reference', flat=True)
        )

        for index, row in enumerate(rows, start=2):
            reference = (row.get('repayment_reference') or '').strip()
            deposit_reference = (row.get('deposit_reference') or f'DEP-{reference}').strip()
            loan_reference = (row.get('loan_reference') or '').strip()
            username = (row.get('username') or '').strip()
            account_label = (row.get('account_label') or '').strip()
            row_errors = []

            if not reference:
                row_errors.append('repayment_reference is required')
            elif len(reference) > 120:
                row_errors.append('repayment_reference is longer than 120 characters')
            elif reference.lower() in seen_references:
                row_errors.append(f'duplicate repayment_reference in file: {reference}')
            else:
                seen_references.add(reference.lower())

            if len(deposit_reference) > 120:
                row_errors.append('deposit_reference is longer than 120 characters')
            if not loan_reference or loan_reference.lower() not in loan_references:
                row_errors.append(f'loan_reference not found: {loan_reference}')

            member = MemberProfile.objects.filter(username=username).first()
            if not member:
                row_errors.append(f'member username not found: {username}')
            elif not SavingsAccount.objects.filter(owner=member, label__iexact=account_label).exists():
                row_errors.append(f'savings account not found for member: {account_label}')

            paid_on = self._parse_date(row.get('paid_on'))
            payment_week = self._parse_date(row.get('payment_week'))
            payment_time = self._parse_time(row.get('payment_time')) or time(0, 0)
            if not paid_on:
                row_errors.append('paid_on is required and must be a valid date')
            if not payment_week:
                row_errors.append('payment_week is required and must be a valid date')

            amount = self._parse_amount(row.get('amount'))
            if amount <= 0:
                row_errors.append('amount must be greater than zero')

            status = 'ERROR' if row_errors else (
                'VALID_EXISTING_REPAYMENT' if reference.lower() in existing_repayments else 'VALID_NEW_REPAYMENT'
            )
            report_index = self._append_report_row(
                report_rows,
                source='repayment',
                row_number=index,
                reference=reference,
                status=status,
                username=username,
                account_label=account_label,
                amount=amount,
                message='; '.join(row_errors),
            )
            if row_errors:
                errors.extend(row_errors)
                continue

            payloads.append(RepaymentPayload(
                row_number=index,
                report_index=report_index,
                reference=reference,
                deposit_reference=deposit_reference,
                loan_reference=loan_reference,
                username=username,
                account_label=account_label,
                paid_on=paid_on,
                payment_week=payment_week,
                payment_time=payment_time,
                amount=amount,
                notes=(row.get('notes') or '').strip(),
            ))

        return payloads, errors

    def _import_loans(self, payloads, report_rows, batch_label):
        imported_at = timezone.now()
        for payload in payloads:
            existing = LoanRequest.objects.filter(import_reference=payload.reference).first()
            if existing:
                self._update_report_row(report_rows, payload.report_index, 'SKIPPED_DUPLICATE', 'loan_reference already exists')
                continue

            member = MemberProfile.objects.get(username=payload.username)
            account = SavingsAccount.objects.get(owner=member, label__iexact=payload.account_label)
            approved_at = timezone.make_aware(datetime.combine(payload.approved_on, time(0, 0)))
            loan = LoanRequest.objects.create(
                member=member,
                account=account,
                principal=payload.principal,
                monthly_interest_rate=payload.monthly_interest_rate,
                duration_months=payload.duration_months,
                purpose=payload.purpose,
                status=LoanRequest.STATUS_APPROVED,
                approved_on=approved_at,
                remarks=payload.remarks or 'Historical loan imported from loan schedule.',
                import_reference=payload.reference,
                import_batch=batch_label,
                imported_at=imported_at,
            )
            LoanRequest.objects.filter(id=loan.id).update(requested_on=approved_at)
            self._update_report_row(report_rows, payload.report_index, 'CREATED_LOAN', 'imported')

    def _import_repayments(self, payloads, report_rows, batch_label, submitted_by):
        imported_at = timezone.now()
        for payload in payloads:
            if LoanRepayment.objects.filter(import_reference=payload.reference).exists():
                self._update_report_row(
                    report_rows,
                    payload.report_index,
                    'SKIPPED_DUPLICATE',
                    'repayment_reference already exists',
                )
                continue

            loan = LoanRequest.objects.select_related('member', 'account').get(import_reference=payload.loan_reference)
            repayment = LoanRepayment(
                loan=loan,
                amount=payload.amount,
                paid_on=payload.paid_on,
                recorded_by=submitted_by,
                notes=payload.notes or 'Historical loan repayment imported from loan schedule.',
                import_reference=payload.reference,
                import_batch=batch_label,
                imported_at=imported_at,
            )
            repayment.full_clean()
            repayment.save()

            if not DepositSubmission.objects.filter(import_reference=payload.deposit_reference).exists():
                deposit = DepositSubmission(
                    member=loan.member,
                    account=loan.account,
                    payment_week=payload.payment_week,
                    starting_week=payload.payment_week,
                    weeks_covered=1,
                    saving_amount=Decimal('0.00'),
                    welfare_amount=Decimal('0.00'),
                    annual_subscription_amount=Decimal('0.00'),
                    membership_amount=Decimal('0.00'),
                    fine_amount=Decimal('0.00'),
                    shares_amount=Decimal('0.00'),
                    loan_repayment_amount=payload.amount,
                    proof='historical_import/no-proof.jpg',
                    remarks=payload.notes or 'Historical loan repayment imported from loan schedule.',
                    payment_date=payload.paid_on,
                    payment_time=payload.payment_time,
                    status='APPROVED',
                    submitted_by=submitted_by,
                    reviewed_by=submitted_by,
                    date_reviewed=imported_at,
                    import_reference=payload.deposit_reference,
                    import_batch=batch_label,
                    imported_at=imported_at,
                )
                deposit.full_clean()
                deposit.save()

            self._update_report_row(report_rows, payload.report_index, 'CREATED_REPAYMENT', 'imported')

    def _load_csv(self, path):
        if not path.exists():
            raise CommandError(f'Import file not found: {path}')
        with path.open(newline='', encoding='utf-8-sig') as handle:
            return list(csv.DictReader(handle))

    def _get_submitted_by(self, username):
        if username:
            user = MemberProfile.objects.filter(username=username).first()
            if not user:
                raise CommandError(f'--submitted-by user not found: {username}')
            return user
        return (
            MemberProfile.objects.filter(role='TREASURER', is_active=True).first()
            or MemberProfile.objects.filter(is_superuser=True).first()
            or MemberProfile.objects.filter(is_active=True).first()
        )

    def _parse_date(self, value):
        text = str(value or '').strip()
        if not text:
            return None
        for date_format in DATE_FORMATS:
            try:
                return datetime.strptime(text, date_format).date()
            except ValueError:
                continue
        return None

    def _parse_time(self, value):
        text = str(value or '').strip()
        if not text:
            return None
        for time_format in TIME_FORMATS:
            try:
                return datetime.strptime(text, time_format).time()
            except ValueError:
                continue
        return None

    def _parse_amount(self, value):
        if value in (None, ''):
            return Decimal('0.00')
        try:
            return Decimal(str(value).replace(',', '').strip())
        except (InvalidOperation, AttributeError):
            return Decimal('0.00')

    def _parse_optional_int(self, value):
        text = str(value or '').strip()
        if not text:
            return None
        try:
            return int(text)
        except ValueError:
            return -1

    def _append_report_row(self, report_rows, source, row_number, reference, status, username, account_label, amount, message):
        report_rows.append({
            'source': source,
            'row_number': row_number,
            'reference': reference,
            'status': status,
            'username': username,
            'account_label': account_label,
            'amount': amount,
            'message': message,
        })
        return len(report_rows) - 1

    def _update_report_row(self, report_rows, index, status, message):
        report_rows[index]['status'] = status
        report_rows[index]['message'] = message

    def _write_report(self, path, rows):
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open('w', newline='', encoding='utf-8') as handle:
            writer = csv.DictWriter(handle, fieldnames=REPORT_FIELDNAMES)
            writer.writeheader()
            writer.writerows(rows)
