# Generated by Django 6.0.4 on 2026-04-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='fine_type',
            field=models.CharField(choices=[('MISSED_WEEKLY_SAVING', 'Missed Weekly Saving'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='fine',
            name='reference_week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
