# Generated by Django 6.0.4 on 2026-05-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_fine_fine_type_fine_reference_week'),
        ('groupcore', '0009_alter_memberprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='groupcore.savingsaccount'),
        ),
    ]
