# Generated by Django 5.2.4 on 2025-07-07 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositsubmission',
            name='for_week',
        ),
        migrations.RemoveField(
            model_name='depositsubmission',
            name='is_manual',
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='starting_week',
            field=models.DateField(default=django.utils.timezone.now, help_text='Week this deposit starts from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='weeks_covered',
            field=models.PositiveIntegerField(default=1, help_text='How many weeks this deposit covers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_group_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_group_deposits', to=settings.AUTH_USER_MODEL),
        ),
    ]
