# Generated by Django 5.2.4 on 2025-07-30 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_remove_depositsubmission_for_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsubmission',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the payment was made'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='payment_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time the payment was made'),
            preserve_default=False,
        ),
    ]
