# Generated by Django 5.2.4 on 2025-07-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_depositsubmission_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsubmission',
            name='proof',
            field=models.ImageField(upload_to='proofs/'),
        ),
    ]
