# Generated by Django 6.0.4 on 2026-04-30 01:54

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_alter_depositsubmission_proof'),
        ('groupcore', '0008_alter_memberprofile_role_savingsaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsubmission',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='groupcore.savingsaccount'),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='payment_week',
            field=models.DateField(default=datetime.date(2026, 1, 1), help_text='Week this saving applies to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='welfare_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='starting_week',
            field=models.DateField(blank=True, help_text='Legacy field: week this deposit starts from', null=True),
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='weeks_covered',
            field=models.PositiveIntegerField(default=1, help_text='Legacy field: how many weeks this deposit covers'),
        ),
    ]
