# Generated by Django 6.0.4 on 2026-05-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0005_depositsubmission_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsubmission',
            name='deposit_purpose',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of deposit purposes (saving, welfare, annual_subscription, fine)', max_length=200),
        ),
    ]
