# Generated by Django 6.0.4 on 2026-05-01 08:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_add_deposit_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositsubmission',
            name='deposit_purpose',
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='annual_subscription_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='depositsubmission',
            name='saving_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='depositsubmission',
            name='welfare_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
