# Generated by Django 6.0.4 on 2026-05-02 20:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0007_per_purpose_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsubmission',
            name='shares_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
