# Generated by Django 5.2.4 on 2025-07-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_acquired', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('DEPOSITS', 'Deposits Cash'), ('INCOME', 'Other Income')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_spent', models.DateField(auto_now_add=True)),
                ('source', models.CharField(choices=[('DEPOSITS', 'Deposits Cash'), ('INCOME', 'Other Income')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
