# Generated by Django 4.2.5 on 2025-07-09 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0002_remove_message_is_read_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='old_recipients',
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='messaging.MessageRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
