# Generated by Django 4.2.5 on 2025-09-03 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0005_alter_message_sender_alter_messagerecipient_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, related_name='received_messages', through='messaging.MessageRecipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
