# Generated by Django 4.2.5 on 2025-09-03 21:09

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_alter_message_sender'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP TABLE IF EXISTS messaging_messagerecipient;
            DROP TABLE IF EXISTS messaging_message;
            DROP TABLE IF EXISTS messaging_message_recipients;
            """,
            reverse_sql=[
                """
                CREATE TABLE messaging_message (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    subject VARCHAR(255) NOT NULL,
                    body TEXT NOT NULL,
                    sent_at DATETIME NOT NULL,
                    sender_id INTEGER NOT NULL,
                    FOREIGN KEY(sender_id) REFERENCES groupcore_memberprofile(id)
                );
                CREATE TABLE messaging_messagerecipient (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    message_id INTEGER NOT NULL,
                    recipient_id INTEGER NOT NULL,
                    is_read INTEGER NOT NULL,
                    FOREIGN KEY(message_id) REFERENCES messaging_message(id),
                    FOREIGN KEY(recipient_id) REFERENCES groupcore_memberprofile(id)
                );
                """
            ]
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=models.CASCADE, related_name='sent_messages', to='groupcore.MemberProfile')),
            ],
            options={'db_table': 'messaging_message'},
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=models.CASCADE, to='messaging.Message')),
                ('recipient', models.ForeignKey(on_delete=models.CASCADE, to='groupcore.MemberProfile')),
            ],
            options={'db_table': 'messaging_messagerecipient'},
        ),
        migrations.AddField(
            model_name='Message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', through='messaging.MessageRecipient', to='groupcore.MemberProfile'),
        ),
    ]
