# Generated by Django 5.2.4 on 2025-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TREASURER', 'Treasurer'), ('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary')], default='MEMBER', max_length=10),
        ),
    ]
