# Generated by Django 5.2.4 on 2025-07-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0002_alter_memberprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_one_start', models.DateField(help_text='The date of the first week (Week 1)')),
            ],
            options={
                'verbose_name': 'Group Setting',
                'verbose_name_plural': 'Group Settings',
            },
        ),
    ]
