# Generated by Django 5.2.4 on 2025-07-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0003_groupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
