# Generated by Django 5.2.4 on 2025-07-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0004_memberprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TREASURER', 'Treasurer'), ('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('Mobilizer', 'Mobilizer')], default='MEMBER', max_length=10),
        ),
    ]
