# Generated by Django 5.2.4 on 2025-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0005_alter_memberprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TREASURER', 'Treasurer'), ('CHAIRMAN', 'Chairman'), ('SECRETARY', 'Secretary'), ('MOBILIZER', 'Mobilizer')], default='MEMBER', max_length=10),
        ),
    ]
