# Generated by Django 4.2.5 on 2025-09-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupcore', '0006_alter_memberprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
